/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMyRouteImport } from './routes/_authed/my'
import { Route as AuthedCareRouteImport } from './routes/_authed/care'
import { Route as AuthedMyScheduleRouteImport } from './routes/_authed/my/schedule'
import { Route as AuthedMyMedicationsRouteImport } from './routes/_authed/my/medications'
import { Route as AuthedCareScheduleRouteImport } from './routes/_authed/care/schedule'
import { Route as AuthedCareMedicationsRouteImport } from './routes/_authed/care/medications'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyRoute = AuthedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCareRoute = AuthedCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyScheduleRoute = AuthedMyScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedMyRoute,
} as any)
const AuthedMyMedicationsRoute = AuthedMyMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AuthedMyRoute,
} as any)
const AuthedCareScheduleRoute = AuthedCareScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedCareRoute,
} as any)
const AuthedCareMedicationsRoute = AuthedCareMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AuthedCareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof AuthedCareRouteWithChildren
  '/my': typeof AuthedMyRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/care/medications': typeof AuthedCareMedicationsRoute
  '/care/schedule': typeof AuthedCareScheduleRoute
  '/my/medications': typeof AuthedMyMedicationsRoute
  '/my/schedule': typeof AuthedMyScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof AuthedCareRouteWithChildren
  '/my': typeof AuthedMyRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/care/medications': typeof AuthedCareMedicationsRoute
  '/care/schedule': typeof AuthedCareScheduleRoute
  '/my/medications': typeof AuthedMyMedicationsRoute
  '/my/schedule': typeof AuthedMyScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_authed/care': typeof AuthedCareRouteWithChildren
  '/_authed/my': typeof AuthedMyRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/_authed/care/medications': typeof AuthedCareMedicationsRoute
  '/_authed/care/schedule': typeof AuthedCareScheduleRoute
  '/_authed/my/medications': typeof AuthedMyMedicationsRoute
  '/_authed/my/schedule': typeof AuthedMyScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/my'
    | '/settings'
    | '/onboarding'
    | '/care/medications'
    | '/care/schedule'
    | '/my/medications'
    | '/my/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/my'
    | '/settings'
    | '/onboarding'
    | '/care/medications'
    | '/care/schedule'
    | '/my/medications'
    | '/my/schedule'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_onboarding'
    | '/_authed/care'
    | '/_authed/my'
    | '/_authed/settings'
    | '/_onboarding/onboarding'
    | '/_authed/care/medications'
    | '/_authed/care/schedule'
    | '/_authed/my/medications'
    | '/_authed/my/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my': {
      id: '/_authed/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthedMyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/care': {
      id: '/_authed/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof AuthedCareRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my/schedule': {
      id: '/_authed/my/schedule'
      path: '/schedule'
      fullPath: '/my/schedule'
      preLoaderRoute: typeof AuthedMyScheduleRouteImport
      parentRoute: typeof AuthedMyRoute
    }
    '/_authed/my/medications': {
      id: '/_authed/my/medications'
      path: '/medications'
      fullPath: '/my/medications'
      preLoaderRoute: typeof AuthedMyMedicationsRouteImport
      parentRoute: typeof AuthedMyRoute
    }
    '/_authed/care/schedule': {
      id: '/_authed/care/schedule'
      path: '/schedule'
      fullPath: '/care/schedule'
      preLoaderRoute: typeof AuthedCareScheduleRouteImport
      parentRoute: typeof AuthedCareRoute
    }
    '/_authed/care/medications': {
      id: '/_authed/care/medications'
      path: '/medications'
      fullPath: '/care/medications'
      preLoaderRoute: typeof AuthedCareMedicationsRouteImport
      parentRoute: typeof AuthedCareRoute
    }
  }
}

interface AuthedCareRouteChildren {
  AuthedCareMedicationsRoute: typeof AuthedCareMedicationsRoute
  AuthedCareScheduleRoute: typeof AuthedCareScheduleRoute
}

const AuthedCareRouteChildren: AuthedCareRouteChildren = {
  AuthedCareMedicationsRoute: AuthedCareMedicationsRoute,
  AuthedCareScheduleRoute: AuthedCareScheduleRoute,
}

const AuthedCareRouteWithChildren = AuthedCareRoute._addFileChildren(
  AuthedCareRouteChildren,
)

interface AuthedMyRouteChildren {
  AuthedMyMedicationsRoute: typeof AuthedMyMedicationsRoute
  AuthedMyScheduleRoute: typeof AuthedMyScheduleRoute
}

const AuthedMyRouteChildren: AuthedMyRouteChildren = {
  AuthedMyMedicationsRoute: AuthedMyMedicationsRoute,
  AuthedMyScheduleRoute: AuthedMyScheduleRoute,
}

const AuthedMyRouteWithChildren = AuthedMyRoute._addFileChildren(
  AuthedMyRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCareRoute: typeof AuthedCareRouteWithChildren
  AuthedMyRoute: typeof AuthedMyRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCareRoute: AuthedCareRouteWithChildren,
  AuthedMyRoute: AuthedMyRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface OnboardingRouteChildren {
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
